### ISSUE TITLE
url() method without item

### ISSUE THREAD

**Issue by vrcAlbert** [novius-os/core#24]
Hello!

I've thought about something which might be helpfull to front developpers. 
Up to now, using urlEnhancer and the url() method is only available with an existing item. It sometimes happens to deal with specific views thanks to an url enhancer without having a specific item.

eg : I have a list of items (default view directly on the page wich contains the url enhancer) or I can display a specific item of this list thanks to `$object->url(...)`, but I may want to display a different kind of list (eg with a filter). The 3rd option should be available by doing something like 

```
\Nos\Tools_Enhancer::url('enhancer_name', array(
    ...
    'params' => array( 
        'some filter/page' => 'some value'
    )
    ...
)); 
```

where the key "params" is used to call the `get_url_model($item, $params)` method of the front controller, with `$item = null`

This would return an url like `www.website.com/path/to/urlenhancer/requested_page.html` whereas now we can only have `www.website.com/path/to/urlenhancer.html`.

Is this sounds acceptable? Or is there another way to do it?

Thanks in advance!

**Comment by felixgilles** [comment]
Hi Victor,

Sorry for delay in this written response, but your issue was still in a corner of my head.

The issue is solved in our dev branch (therefore officialy, with the future version Chiba 2).

The changes:
- The method get_url_model($item, $params) in enhancer front controller is deprecated, use instead getURLEnhanced($params) and $item in a key "item" of $params ($item is optionnal).
- The Tools_Enhancer::urls() method now calls getURLEnhanced() to get a possible URL enhanced.

**Comment by vrcAlbert** [comment]
Thanks! This should indeed do the job :)
